### PR TITLE
Fix for IoRing shutdown hang bug.

### LINKED ISSUE #143: IoRing::run() hang when called from multiple threads (sporadic)
`IoRing::run()` may fail to return when the work count goes to zero or when `IoRing::stop()` is called.  This is causing `IoRingTest.EnqueueManyHandlers` (src/llfs/ioring.test.cpp) to hang every few thousand times it runs.

### PR DESCRIPTION
**Pull request by tonyastolfi**
Fixes #143 

Changed the EnqueueManyHandlers test to run repeatedly in a loop 5000 times.  In interactive testing, this triggers the bug about 80% of the time, so I think its a good compromise between catching regressions and keeping the tests fast.

Recommend starting with the comment in the newly added `IoRingImpl::wake_all()` function.

### CODE REVIEW

File: src/llfs/ioring_impl.cpp [hunk 1]
```diff
@@ -671,6 +661,61 @@ Status IoRingImpl::unregister_files_with_lock(const std::unique_lock<std::mutex>
...
+  // sections (for this->queue_mutex_).  In other words, either B1.5 happens-before A1 or B1.5
+  // happens-after A3:
+  //
+  //   - If B1.5 happens-before A1, then B1 also happens-before A2, which means A2 can't observe the
+  //     pre-B1 value of the work counter.
+  //   - If B1.5 happens-after A3, then B2 also happens-after A3, which means B2 will interrupt the
+  //     condition wait.
+  //
+  {
+    std::unique_lock<std::mutex> queue_lock{this->queue_mutex_};
```
Comment (gabrielbornstein) [inline src/llfs/ioring_impl.cpp:703]: Since this line is reasonably counter-intuitive for me, is there any other way we can acquire the same effect through a different  implementation? Would it do significant harm to expand the scope of queue_lock to be the size of the function?

**Review by gabrielbornstein — APPROVED** [review]
Really great explanatory comments. Overall, the code is easier to read with these changes.

File: src/llfs/ioring_impl.cpp [hunk 2]
```diff
@@ -217,6 +203,12 @@ Status IoRingImpl::run() noexcept
         // eventfd_read, UNLESS handler is nullptr.  So in that case, wake up a waiting thread.
         //
         if (handler == nullptr) {
+          {
+            // See comment in IoRingImpl::wake_all() for an explanation of why this seemingly
+            // unproductive statement is necessary.
+            //
+            std::unique_lock<std::mutex> queue_lock{this->queue_mutex_};
```
[the remark this answers is not in the document]
Comment (tonyastolfi) [reply src/llfs/ioring_impl.cpp:210]: My concern is that a future maintainer might see this odd looking fragment that appears to do nothing, assume it is a mistake, and remove it without realizing that it actually does perform an essential role.

File: src/llfs/ioring_impl.cpp (hunk 1 above)
Comment (tonyastolfi) [reply src/llfs/ioring_impl.cpp:703]: "...is there any other way..."  Of course... the real question is what specific alternative would you propose?  Being counter-intuitive is a mixture of objective and subjective factors (perhaps more accurately, of collective subjective and individual subjective).  The intention for the explanation here is that the code gives the reader a chance to re-calibrate his/her/their intuitions.

Extending the scope of the lock to the entire function is likely to be a pessimization, as mentioned by the documentation for std::condition_variable found here: https://en.cppreference.com/w/cpp/thread/condition_variable/notify_all

The point they are making is that, since the notify is intended to wake other thread(s), doing the notify before unlocking the mutex can create a race between unlocking and re-locking by the receiver(s) of the notification, which could induce extra context swaps and scheduling overhead.  Not ideal.  

Really, this entire thing is a performance optimization, since we could, for example, use `queue_mutex_` to protect a regular integer counter for the work count, instead of having `work_count_` be an atomic.  For me, I think the real takeaway from this bug is that you can never afford to completely skip the mutex lock/unlock step before issuing a notification, even if whatever state is modified such that the wait condition needs to be rechecked is protected against data races in some other way (i.e., it is just an atomic instruction).  We can just add that to our effective model of how to use condition variables without needing a deeper understanding of what can go wrong when we don't follow the pattern.
