### PR TITLE
Page allocator fixes

### LINKED ISSUE #19: PageRefCount should use PageId strong type
Right now it is using `page_id_int`, which is a simple (weak) type alias, to represent a page id.  It would be better to use PageId, since this will prevent accidental substitution of a compatible integer value that does not represent page id; when using `page_id_int`, the mistake will not be caught by the compiler, and there will be a (possibly mysterious and downstream) error at runtime, or worse, incorrect behavior.  With this change, the code will simply fail to compile (with a type error) if this mistake is made.

### LINKED ISSUE #20: Add a simple impl of LogDeviceFactory that wraps a function returning std::unique_ptr<LogDevice>
The existing LogDeviceFactory interface is a little cumbersome when all one wants is to just create a LogDevice object, e.g., within a test.  We can fix this by having an implementation that simply wraps `std::function<std::unique_ptr<llfs::LogDevice>()>`.

### LINKED ISSUE #21: PackedPageId should support `get_page_id`, `unpack_cast`.
`PageId get_page_id(const T& obj)` is an overloaded function set interface that allows generic programming against collections of objects that have a natural association with a PageId.  `PackedPageId` is of course a natural fit, and it would be convenient if it supported this interface.

`unpack_cast` is the new preferred method of deserialization for packed types, since it is faster than `unpack_object` (which requires a copy/move of the deserialized type in the return value), and it is safer than simply using `reinterpret_cast<const T&>` (or C-style casting), which while correct, fails to detect buffer overrun errors (which is the explicit purpose of `unpack_cast`).  Supporting `unpack_cast` involves implementing `Status validate_packed_object(const T&, const void*, usize)` for a given type.

### LINKED ISSUE #22: PageAllocator::update_page_ref_counts doesn't assign unique/deterministic ownership of dead pages.
This method's signature is:

```c++
template <typename PageRefCountSeq, typename GarbageCollectFn>
StatusOr<slot_offset_type> update_page_ref_counts(
    const boost::uuids::uuid& user_id, slot_offset_type user_slot,
    PageRefCountSeq&& ref_count_updates, GarbageCollectFn&& garbage_collect_fn);
```

The intended behavior for the last parameter, `garbage_collect_fn`, is that it be invoked for all PageIds whose reference count was decreased to 1 as a result of this update.  (It is invalid to decrease a reference count to a negative value, for obvious reasons, and the only valid way to go from a positive value to zero is to use the special value kRefCount_1_to_0, which requires the current ref count to be 1, indicating that the caller is the unique owner of the page.  In both cases, the implementation should panic if the rule is violated.)

Pages with a ref count of exactly 1 are "dead" pages; they must be given to a PageRecycler so that any pages referenced from them can be decremented prior to dropping the page and allowing re-allocation of the backing storage resources.

However, because PageAllocator keeps no record of the most recent client to update a ref count, it has no way of reliably inferring whether a given caller was actually the one that caused a page to become dead.  Therefore, it is possible during recovery for a _different_ client to be notified of the dead page; thus two distinct clients may attempt to recycle the same page, and Bad Things follow.  

The plan for fixing this is to introduce an "attachment number" `u32` that uniquely identifies an attachment in the context of a PageAllocator, and use this to mark all Txns and PackedPageRefCount refresh slots (checkpoint slices).

### LINKED ISSUE #23: PageAllocatorState is not given the configured `max_attachments` when created.
Therefore it has no way of enforcing this limit on the maximum number of attached clients for a PageAllocator.  This is bad because the limit is how we guarantee that the LogDevice that backs the PageAllocator doesn't run out of space and deadlock.

### LINKED ISSUE #25: Panic while recovering PageAllocator state from log due to event re-ordering.
The existing recovery code attempts to use the same logic as post-recovery (steady-state) changes to the PageAllocatorState; specifically, we want to check that any "learned" event that specifies a client `user_id` (uuid) references a currently attached client.  However, because checkpoint slices are written in LRU order, it is possible for the attach event that signals a client (uuid) is attached to be re-ordered _after_ events that reference that client (e.g., PackedPageAllocatorTxn).  

We can fix this by having two distinct code paths, one for recovery and one for steady-state, and deferring all consistency checks in the recovery path until the end, when the in-memory PageAllocatorState should observe all the expected invariants.

### LINKED ISSUE #26: PageAllocator should suspend all page allocations until any unresolved Volume jobs have committed/aborted.
It is possible for a Volume to get halfway through committing a PageCacheJob, having written the PrepareJob slot, written all new page data to the corresponding PageDevice, and updated at least one set of ref counts in a PageAllocator.  If, however, not all PageAllocators involved in the job have been updated with the new ref counts, then a new page which should not be available for allocation, since the job is going to commit, might still be in the `free_pool` list for its PageAllocator.  If this happens, it is crucial that the PageAllocator **not** hand out this page to another client, since this would cause incoherence of the page data.  

To fix this, we will introduce a "client recovery" initial state in PageAllocator.  If the PageAllocator has _any_ attached clients, it will enter "client recovery" when it is recovered.  Most PageAllocator operations will not be affected by "client recovery" state; however, any attempts to allocate a page will either fail or block until all attached clients have notified the PageAllocator that they have resolved all pending jobs.

### LINKED ISSUE #27: PageAllocator ref_counts incorrect after recovery
This is happening because we are always updating the `last_updated` slot for a page ref count inside `void PageAllocatorState::learn(const SlotRange& slot_offset, const PackedPageAllocatorTxn& op, PageAllocatorMetrics&)`.  The problem is that only in a couple of boundary cases is the information in a single Txn sufficient (by itself) to calculate the true value of a ref count.  In particular, a Txn only contains deltas, which need the prior value to be accurate.  

The solution is to only set the last updated slot when a Txn contains `kRefCount_1_to_0` (after which we can be sure that the ref count is 0), or if the page isn't in the LRU list, which implies that it was last updated at slot offset zero, when by definition the count value is zero.

### LINKED ISSUE #28: PackedPageRefCount events read during PageAllocator recovery do not update free_pool list status
This leads to incorrect behavior where a page can be assumed to be free when it is not, and when a page can be assumed in use when it is free (leak).

`PageAllocatorState::learn` is responsible for processing all page ref checkpoint slices during recovery; since it expects to never see any changes to state during normal (post-recovery) operation, it doesn't ever bother to check that the free pool linked list status of the object matches its ref count like it should (during recovery, anyhow).

### PR DESCRIPTION
**Pull request by tonyastolfi**
This PR fixes many recovery-related PageAllocator bugs, addresses some long-standing code improvement TODOs, and adds test coverage to PageAllocator to verify the fixes.

Fixes #19 
Fixes #20 
Fixes #21
Fixes #22
Fixes #23 
Fixes #25 
Fixes #26 
Fixes #27 
Fixes #28

### CODE REVIEW

File: src/llfs/page_ref_count.hpp [hunk 1]
```diff
@@ -20,15 +20,13 @@
...
 
 struct PageRefCount {
-  // TODO [tastolfi 2021-09-07] - change `page_id` to type `PageId` for stronger
-  // type checking.
-  page_id_int page_id;
+  PageId page_id;
   i32 ref_count;
 
   struct Delta {
     PageRefCount operator()(page_id_int page_id) const
```
Comment (tonyastolfi) [inline src/llfs/page_ref_count.hpp:27]: Add TODO here?

File: src/llfs/page_allocator_attachment.hpp [hunk 2]
```diff
@@ -0,0 +1,113 @@
...
+   */
+  u32 get_user_index() const noexcept
+  {
+    return this->user_index_;
+  }
+
+ private:
+  const boost::uuids::uuid user_id_;
+  slot_offset_type user_slot_;
+  u32 user_index_;
```
Comment (tonyastolfi) [inline src/llfs/page_allocator_attachment.hpp:79]: Maybe this should be const?

File: src/llfs/page_allocator_state.cpp [hunk 3]
```diff
@@ -420,18 +472,25 @@ void PageAllocatorState::learn(slot_offset_type index_slot, const PackedPageAllo
...
     const page_id_int physical_page = this->page_ids_.get_physical_page(page_id);
     PageAllocatorRefCount* const obj = &this->page_ref_counts_[physical_page];
-    this->learn_ref_count_delta(delta, obj, metrics);
-    this->set_last_update(obj, index_slot);
+
+    obj->set_last_modified_by(txn.user_index);
+
+    this->learn_ref_count_delta(slot_offset, delta, obj, metrics);
+
+    if (delta.ref_count == kRefCount_1_to_0 || !obj->PageAllocatorLRUHook::is_linked()) {
```
Comment (tonyastolfi) [inline src/llfs/page_allocator_state.cpp:480]: The fix to #25

Comment (bhaskarbora2) [reply src/llfs/page_allocator_state.cpp:480]: May be we can think of collapsing all (past) updates into the new one so that we can remove our past dependencies. Alternatively, we can always write a whole record which is fully qualified to generate the latest value of the ref count.

File: src/llfs/page_allocator.hpp [hunk 4]
```diff
@@ -111,14 +112,14 @@ class PageAllocator
...
   // Updates the index synchronously by applying the specified event.  Must be one of the event
   // types enumerated in page_device_event_types.hpp.
   // TODO [tastolfi 2023-03-22] deprecate public usage of this function!
   //
   template <typename T>
-  StatusOr<slot_offset_type> update_sync(const T& event);
+  StatusOr<slot_offset_type> update_sync(T& event);
 
   // Block until updates have caught up with the specified slot number.
   //
```
Comment (tonyastolfi) [inline src/llfs/page_allocator.hpp:125]: Add comment to doc of `update_page_ref_counts`: only the ***last*** delta for a given `page_id` in the sequence (`ref_count_updates`) will be applied, earlier ones are ignored.

File: src/llfs/page_allocator_state.cpp [hunk 5]
```diff
@@ -438,9 +456,31 @@ Status PageAllocatorState::recover(const SlotRange& slot_offset,
...
+  if (status == ProposalStatus::kValid) {
+    for (PackedPageRefCount& prc : txn->ref_counts) {
+      prc.ref_count = this->calculate_new_ref_count(prc);
+    }
+  }
+
+  return status;
 }
 
 //----- --- -- -  -  -   -
```
Comment (tonyastolfi) [inline src/llfs/page_allocator_state.cpp:486]: Try to unify most of the logic in `learn(txn)` and `recover(txn)`

File: src/llfs/page_allocator.hpp (hunk 4 above)
Comment (tonyastolfi) [reply src/llfs/page_allocator.hpp:125]: Added.

File: src/llfs/page_allocator_state.cpp (hunk 5 above)
Comment (tonyastolfi) [reply src/llfs/page_allocator_state.cpp:497]: Done.

**Review by bhaskarbora2 — APPROVED** [review]
Moving ahead with the review step.
